### ISSUE TITLE
Reloading CSS in place with LiveReload

### ISSUE THREAD

**Issue by OliverJAsh** [webxl/grunt-reload#26]
```
...
    port: 35729, // LR default
    liveReload: {}
...
```

This is what the docs state – what is the object supposed to be? According to the docs, `liveReload` should just be a boolean.

When changes are made to a CSS file, the whole page is reloaded instead of just the CSS file. I thought this wasn't supposed to happen?

**Comment by xrado** [comment]
+1

**Comment by webxl** [comment]
The problem is that grunt-contrib-watch doesn't pass the names of the files that have been updated. I did find a work around, however. See https://github.com/gruntjs/grunt-contrib-watch/issues/14#issuecomment-12704238
