### ISSUE TITLE
Problem with livereload 1.6

### ISSUE THREAD

**Issue by maksimr** [webxl/grunt-reload#4]
Hello.

I installed grunt-reload and extension in firefox livereload.

Then I wrote in my grunt.js

``` js

...
reload: {
      port: 35729
}
...

```

Runt command `grunt reload watch`, enable livereload button in browser.

And when I change any files I get alert in browser:

```
You are using an old incompatible version of the command-line tool.

Please run the following command to update your command-line tool:
    gem update livereload

```

But If use gem livereload it's work fine.

```

grunt version 0.3.9
livereload 0.6.4 (Firefox addon)
Firefox 13.0.1
OS Ubuntu
protocol 'file:'

```

Where I made a mistake?
Thanks!

**Comment by manoharank** [comment]
@maksimr did you find the solution?

**Comment by maksimr** [comment]
Yes now I use [yeoman](https://github.com/yeoman/yeoman) ;)

**Comment by pajtai** [comment]
That's not really a solution to this problem.

**Comment by d48** [comment]
yeoman injects the livereload.js file into the *.html file that you are browsing from using `yeoman server` that spins up a web server instance.  I'm having issues trying to configure `reload` task with `server` as well

I can however use the Chrome extension by enabling it from setting `reload: { port: 35279 }` in grunt.js file and enabling the LiveReload extension once a web server instance is spun up

**Comment by omargourari** [comment]
I'm experiencing the same problem of maksimr.
Did someone find a reliable solution?
I'm using Firefox (and the Livereload add-on) and Grunt.
While in the watching mode it detects changes to any file choosen in the Gruntfile.js but, when it has to push changes to the browser a message appear with the following warning:

You are using an old incompatible version of the command-line tool.

Please run the following command to update your command-line tool:
    gem update livereload

Thank you

**Comment by d48** [comment]
@omargourari check out the newer versions of grunt that use `grunt-contrib-watch`

Also make sure you're using the Livereload Firefox extension found here: http://feedback.livereload.com/knowledgebase/articles/86242-how-do-i-install-and-use-the-browser-extensions-

I have a sampler repo you can clone and `npm install` then `npm start` to try

https://github.com/d48/grunt-watch-boilerplate
